export const examplePlansPayload = {
  object: "list",
  data: [
    {
      id: "plan_GZIYxMWHBwjwgR",
      object: "plan",
      active: true,
      aggregate_usage: null,
      amount: 49,
      amount_decimal: "4900",
      billing_scheme: "per_unit",
      created: 1570142400,
      currency: "usd",
      interval: "month",
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: "Personal Plan",
      product: {
        id: "prod_GRUiOw3cReZAew",
        object: "product",
        active: true,
        attributes: [],
        caption: null,
        created: 1570142365,
        deactivate_on: [],
        description: null,
        images: [],
        livemode: false,
        metadata: {},
        name: "Personal",
        package_dimensions: null,
        shippable: null,
        statement_descriptor: null,
        type: "service",
        unit_label: null,
        updated: 1570142401,
        url: null
      },
      tiers: null,
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "licensed"
    },
    {
      id: "plan_GZIdU6HqG8vkcA",
      object: "plan",
      active: true,
      aggregate_usage: null,
      amount: 99,
      amount_decimal: "9900",
      billing_scheme: "per_unit",
      created: 1570215199,
      currency: "usd",
      interval: "month",
      interval_count: 1,
      livemode: false,
      metadata: {},
      nickname: "Professional Plan",
      product: {
        id: "prod_GRUiOw3cReZAew",
        object: "product",
        active: true,
        attributes: [],
        caption: null,
        created: 1570142433,
        deactivate_on: [],
        description: null,
        images: [],
        livemode: false,
        metadata: {},
        name: "Professional",
        package_dimensions: null,
        shippable: null,
        statement_descriptor: null,
        type: "service",
        unit_label: null,
        updated: 1570215201,
        url: null
      },
      tiers: null,
      tiers_mode: null,
      transform_usage: null,
      trial_period_days: null,
      usage_type: "licensed"
    }
  ],
  has_more: false,
  url: "/v1/plans"
};
